---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - customjobs.mshyshov.site
  resources:
  - scheduledjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customjobs.mshyshov.site
  resources:
  - scheduledjobs/finalizers
  verbs:
  - update
- apiGroups:
  - customjobs.mshyshov.site
  resources:
  - scheduledjobs/status
  verbs:
  - get
  - patch
  - update
